apiVersion: v2
name: chromium
description: La distribution open source du navigateur Google Chrome.
icon: https://etalab.github.io/helm-charts-sill/icons/chromium.svg
keywords:
  - Navigateur
home: https://www.chromium.org/chromium-projects/
sources:
  - https://github.com/chromium/chromium
  - https://github.com/etalab/helm-charts-sill/tree/main/charts/chromium
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.0.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: latest

dependencies:
  - name: library-chart
    version: 2.1.0
    repository: https://inseefrlab.github.io/helm-charts-datascience
